site_name: OGC API Leermodule
site_url: https://www.acceptatie.pdok.nl/leermodule
site_description: Een leermodule met achtergrondinformatie en oefeningen om te leren werken met OGC API's van PDOK
repo_url: https://github.com/PDOK/leermodule-ogc-api/
edit_uri: edit/master/docs/

nav:
    - Introductie: index.md
    - Achtergrondinformatie: Achtergrondinformatie.md
    - OGC API - Tiles: 
        - Introductie: tiles/Introductie.md
        - Verken OGC API - Tiles in de browser: tiles/Verken OGC API - Tiles in de browser.md
        - Maak een kaart met OGC API - Tiles: tiles/Maak een kaart met OGC API - Tiles.md
        - Terugblik: tiles/Terugblik.md
    - OGC API - Features:
        - Introductie: features/Introductie.md
        - Verken OGC API - Features in de browser: features/Verken OGC API - Features.md
        - Bevraag OGC API - Features met curl: features/Bevraag OGC API - Features met curl.md
        - Maak een interactieve kaart met OGC API - Features: features/Maak een interactieve kaart met OGC API - Features.md
        - Terugblik: features/Terugblik.md
    - Afronding: Afronding.md
    - Referenties:
        - Verwijzingen: referenties/features.md 

